//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Рабочее место.
    /// </summary>
    // *** Start programmer edit section *** (РабочееМесто CustomAttributes)

    // *** End programmer edit section *** (РабочееМесто CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РабочееМестоE", new string[] {
            "ИнвНомер as \'Инв номер\'",
            "Кабинет as \'Кабинет\'",
            "Место as \'Место\'"})]
    [AssociatedDetailViewAttribute("РабочееМестоE", "Оборудование", "ОборудованиеE", true, "", "Оборудование", true, new string[] {
            ""})]
    [View("РабочееМестоL", new string[] {
            "ИнвНомер as \'Инв номер\'",
            "Кабинет as \'Кабинет\'",
            "Место as \'Место\'"})]
    public class РабочееМесто : ICSSoft.STORMNET.DataObject
    {
        
        private string fИнвНомер;
        
        private string fКабинет;
        
        private string fМесто;
        
        private IIS.ISS6.DetailArrayOfОборудование fОборудование;
        
        // *** Start programmer edit section *** (РабочееМесто CustomMembers)

        // *** End programmer edit section *** (РабочееМесто CustomMembers)

        
        /// <summary>
        /// ИнвНомер.
        /// </summary>
        // *** Start programmer edit section *** (РабочееМесто.ИнвНомер CustomAttributes)

        // *** End programmer edit section *** (РабочееМесто.ИнвНомер CustomAttributes)
        [StrLen(255)]
        public virtual string ИнвНомер
        {
            get
            {
                // *** Start programmer edit section *** (РабочееМесто.ИнвНомер Get start)

                // *** End programmer edit section *** (РабочееМесто.ИнвНомер Get start)
                string result = this.fИнвНомер;
                // *** Start programmer edit section *** (РабочееМесто.ИнвНомер Get end)

                // *** End programmer edit section *** (РабочееМесто.ИнвНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РабочееМесто.ИнвНомер Set start)

                // *** End programmer edit section *** (РабочееМесто.ИнвНомер Set start)
                this.fИнвНомер = value;
                // *** Start programmer edit section *** (РабочееМесто.ИнвНомер Set end)

                // *** End programmer edit section *** (РабочееМесто.ИнвНомер Set end)
            }
        }
        
        /// <summary>
        /// Кабинет.
        /// </summary>
        // *** Start programmer edit section *** (РабочееМесто.Кабинет CustomAttributes)

        // *** End programmer edit section *** (РабочееМесто.Кабинет CustomAttributes)
        [StrLen(255)]
        public virtual string Кабинет
        {
            get
            {
                // *** Start programmer edit section *** (РабочееМесто.Кабинет Get start)

                // *** End programmer edit section *** (РабочееМесто.Кабинет Get start)
                string result = this.fКабинет;
                // *** Start programmer edit section *** (РабочееМесто.Кабинет Get end)

                // *** End programmer edit section *** (РабочееМесто.Кабинет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РабочееМесто.Кабинет Set start)

                // *** End programmer edit section *** (РабочееМесто.Кабинет Set start)
                this.fКабинет = value;
                // *** Start programmer edit section *** (РабочееМесто.Кабинет Set end)

                // *** End programmer edit section *** (РабочееМесто.Кабинет Set end)
            }
        }
        
        /// <summary>
        /// Место.
        /// </summary>
        // *** Start programmer edit section *** (РабочееМесто.Место CustomAttributes)

        // *** End programmer edit section *** (РабочееМесто.Место CustomAttributes)
        [StrLen(255)]
        public virtual string Место
        {
            get
            {
                // *** Start programmer edit section *** (РабочееМесто.Место Get start)

                // *** End programmer edit section *** (РабочееМесто.Место Get start)
                string result = this.fМесто;
                // *** Start programmer edit section *** (РабочееМесто.Место Get end)

                // *** End programmer edit section *** (РабочееМесто.Место Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РабочееМесто.Место Set start)

                // *** End programmer edit section *** (РабочееМесто.Место Set start)
                this.fМесто = value;
                // *** Start programmer edit section *** (РабочееМесто.Место Set end)

                // *** End programmer edit section *** (РабочееМесто.Место Set end)
            }
        }
        
        /// <summary>
        /// Рабочее место.
        /// </summary>
        // *** Start programmer edit section *** (РабочееМесто.Оборудование CustomAttributes)

        // *** End programmer edit section *** (РабочееМесто.Оборудование CustomAttributes)
        public virtual IIS.ISS6.DetailArrayOfОборудование Оборудование
        {
            get
            {
                // *** Start programmer edit section *** (РабочееМесто.Оборудование Get start)

                // *** End programmer edit section *** (РабочееМесто.Оборудование Get start)
                if ((this.fОборудование == null))
                {
                    this.fОборудование = new IIS.ISS6.DetailArrayOfОборудование(this);
                }
                IIS.ISS6.DetailArrayOfОборудование result = this.fОборудование;
                // *** Start programmer edit section *** (РабочееМесто.Оборудование Get end)

                // *** End programmer edit section *** (РабочееМесто.Оборудование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РабочееМесто.Оборудование Set start)

                // *** End programmer edit section *** (РабочееМесто.Оборудование Set start)
                this.fОборудование = value;
                // *** Start programmer edit section *** (РабочееМесто.Оборудование Set end)

                // *** End programmer edit section *** (РабочееМесто.Оборудование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РабочееМестоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РабочееМестоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РабочееМестоE", typeof(IIS.ISS6.РабочееМесто));
                }
            }
            
            /// <summary>
            /// "РабочееМестоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РабочееМестоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РабочееМестоL", typeof(IIS.ISS6.РабочееМесто));
                }
            }
        }
    }
}
